"""init tables

Revision ID: 3e5c3a3fa197
Revises: 
Create Date: 2025-08-27 20:30:54.407080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e5c3a3fa197'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('friends', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('friends', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('friends', 'friend_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_friends_id'), 'friends', ['id'], unique=False)
    op.add_column('group_members', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('group_members', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('group_members', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('group_members', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.add_column('groups', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('groups', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.alter_column('groups', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'owner_id')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.alter_column('group_members', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('group_members', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('group_members', 'joined_at')
    op.drop_column('group_members', 'role')
    op.drop_index(op.f('ix_friends_id'), table_name='friends')
    op.alter_column('friends', 'friend_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('friends', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('friends', 'created_at')
    op.drop_column('friends', 'status')
    # ### end Alembic commands ###
